/*
 * vocab.js — 500 palabras más frecuentes del alemán
 * Formato: [palabra, género, traducción, pronunciación-ES, ej1_de, ej1_es, ej2_de, ej2_es, ej3_de, ej3_es]
 * Género: "der" | "die" | "das" | "" (verbos, adjetivos, palabras funcionales)
 */
const VOCAB_RAW = [
  // ── 1-10: Verbos esenciales ───────────────────────────────────────────────
  ["sein","","ser / estar","sain","Ich bin müde.","Estoy cansada.","Das ist schön.","Eso es bonito.","Wir sind hier.","Estamos aquí."],
  ["haben","","tener","ja-ben","Ich habe Hunger.","Tengo hambre.","Sie hat ein Auto.","Ella tiene un coche.","Wir haben Zeit.","Tenemos tiempo."],
  ["werden","","volverse / futuro","vér-den","Es wird kalt.","Se está poniendo frío.","Ich werde lernen.","Voy a estudiar.","Du wirst besser.","Mejorarás."],
  ["können","","poder","kö-nen","Ich kann Deutsch.","Sé alemán.","Kannst du kommen?","¿Puedes venir?","Wir können helfen.","Podemos ayudar."],
  ["müssen","","deber / tener que","mü-sen","Ich muss arbeiten.","Tengo que trabajar.","Du musst essen.","Tienes que comer.","Wir müssen gehen.","Tenemos que irnos."],
  ["wollen","","querer","vó-len","Ich will Kaffee.","Quiero café.","Was willst du?","¿Qué quieres?","Wir wollen reisen.","Queremos viajar."],
  ["sollen","","deber (obligación externa)","zó-len","Du sollst nicht lügen.","No debes mentir.","Was soll ich tun?","¿Qué debo hacer?","Er soll kommen.","Se supone que viene."],
  ["dürfen","","poder (permiso)","dür-fen","Darf ich?","¿Puedo / me permite?","Hier darf man nicht rauchen.","Aquí no se puede fumar.","Du darfst bleiben.","Puedes quedarte."],
  ["mögen","","gustar / querer","mö-gen","Ich mag Musik.","Me gusta la música.","Magst du Pizza?","¿Te gusta la pizza?","Sie mögen Tiere.","Les gustan los animales."],
  ["machen","","hacer","má-jen","Was machst du?","¿Qué haces?","Ich mache Pause.","Hago una pausa.","Wir machen Sport.","Hacemos deporte."],

  // ── 11-30: Verbos frecuentes ──────────────────────────────────────────────
  ["gehen","","ir (a pie)","gué-en","Ich gehe nach Hause.","Voy a casa.","Wohin gehst du?","¿Adónde vas?","Wir gehen zusammen.","Vamos juntos."],
  ["kommen","","venir","kó-men","Woher kommst du?","¿De dónde eres?","Er kommt morgen.","Viene mañana.","Komm rein!","¡Entra!"],
  ["sagen","","decir","zá-gen","Was sagst du?","¿Qué dices?","Er sagt die Wahrheit.","Él dice la verdad.","Sag mir bitte.","Dime por favor."],
  ["sehen","","ver","zé-en","Ich sehe dich.","Te veo.","Siehst du das?","¿Ves eso?","Wir sehen einen Film.","Vemos una película."],
  ["geben","","dar","gué-ben","Gib mir das bitte.","Dame eso por favor.","Er gibt mir Geld.","Me da dinero.","Was gibt es?","¿Qué hay?"],
  ["nehmen","","tomar / coger","né-men","Ich nehme den Bus.","Tomo el autobús.","Nimm das!","¡Coge eso!","Sie nimmt Kaffee.","Ella pide café."],
  ["kommen","","llegar","kó-men","Wann kommst du an?","¿Cuándo llegas?","Der Zug kommt.","El tren llega.","Ich komme später.","Llego más tarde."],
  ["wissen","","saber (un hecho)","ví-sen","Ich weiß nicht.","No sé.","Weißt du das?","¿Sabes eso?","Er weiß alles.","Él lo sabe todo."],
  ["kennen","","conocer (a alguien)","ké-nen","Kennst du sie?","¿La conoces?","Ich kenne Berlin.","Conozco Berlín.","Wir kennen uns.","Nos conocemos."],
  ["denken","","pensar","dénk-en","Ich denke an dich.","Pienso en ti.","Was denkst du?","¿Qué piensas?","Ich denke, ja.","Creo que sí."],

  ["lassen","","dejar / permitir","lá-sen","Lass mich!","¡Déjame!","Ich lasse das.","Lo dejo.","Lass uns gehen.","Vámonos."],
  ["stehen","","estar de pie / poner","sté-en","Ich stehe auf.","Me levanto.","Wie steht es?","¿Cómo va?","Es steht geschrieben.","Está escrito."],
  ["heißen","","llamarse","hái-sen","Ich heiße Olga.","Me llamo Olga.","Wie heißt du?","¿Cómo te llamas?","Das heißt viel.","Eso significa mucho."],
  ["bleiben","","quedarse / seguir","bláy-ben","Bleib hier!","¡Quédate aquí!","Ich bleibe zu Hause.","Me quedo en casa.","Bleibt ruhig.","Quedaos tranquilos."],
  ["sprechen","","hablar","sprék-en","Ich spreche Deutsch.","Hablo alemán.","Sprechen Sie Englisch?","¿Habla inglés?","Wir sprechen viel.","Hablamos mucho."],
  ["finden","","encontrar / opinar","fín-den","Ich finde es gut.","Me parece bien.","Hast du es gefunden?","¿Lo encontraste?","Findest du das schön?","¿Te parece bonito?"],
  ["glauben","","creer","gláu-ben","Ich glaube nicht.","No lo creo.","Glaubst du das?","¿Te lo crees?","Ich glaube dir.","Te creo."],
  ["halten","","parar / sostener / opinar","hál-ten","Halt!","¡Para!","Ich halte das für falsch.","Creo que eso está mal.","Der Bus hält hier.","El autobús para aquí."],
  ["liegen","","estar tumbado / estar ubicado","lí-gen","Wo liegt das?","¿Dónde está eso?","Ich liege im Bett.","Estoy en la cama.","Berlin liegt in Deutschland.","Berlín está en Alemania."],
  ["zeigen","","mostrar / señalar","tsái-gen","Zeig mir das!","¡Muéstrame eso!","Er zeigt mir den Weg.","Me muestra el camino.","Was zeigt die Karte?","¿Qué muestra el mapa?"],

  // ── 31-50: Más verbos ─────────────────────────────────────────────────────
  ["fragen","","preguntar","frá-gen","Darf ich fragen?","¿Puedo preguntar?","Sie fragt mich.","Ella me pregunta.","Frag ihn!","¡Pregúntale!"],
  ["antworten","","responder / contestar","ánt-vor-ten","Bitte antworte mir.","Por favor respóndeme.","Er antwortet nicht.","Él no contesta.","Wie antwortest du?","¿Cómo respondes?"],
  ["arbeiten","","trabajar","ár-bay-ten","Ich arbeite viel.","Trabajo mucho.","Wo arbeitest du?","¿Dónde trabajas?","Sie arbeitet morgen.","Ella trabaja mañana."],
  ["lernen","","aprender / estudiar","lér-nen","Ich lerne Deutsch.","Aprendo alemán.","Lernst du für die Prüfung?","¿Estudias para el examen?","Man lernt nie aus.","Nunca se deja de aprender."],
  ["spielen","","jugar / tocar (instrumento)","spí-len","Ich spiele Gitarre.","Toco la guitarra.","Die Kinder spielen.","Los niños juegan.","Spielst du Fußball?","¿Juegas al fútbol?"],
  ["schreiben","","escribir","shráy-ben","Ich schreibe dir.","Te escribo.","Schreib das auf!","¡Apunta eso!","Sie schreibt gut.","Ella escribe bien."],
  ["lesen","","leer","lé-zen","Ich lese gern.","Me gusta leer.","Liest du das Buch?","¿Lees el libro?","Er liest jeden Tag.","Él lee cada día."],
  ["hören","","escuchar / oír","hö-ren","Ich höre Musik.","Escucho música.","Hörst du mich?","¿Me oyes?","Hör mal!","¡Escucha!"],
  ["verstehen","","entender","fer-stéen","Ich verstehe nicht.","No entiendo.","Verstehst du mich?","¿Me entiendes?","Das verstehe ich gut.","Eso lo entiendo bien."],
  ["kaufen","","comprar","káu-fen","Ich kaufe Brot.","Compro pan.","Was kaufst du?","¿Qué compras?","Sie kauft Kleidung.","Ella compra ropa."],

  ["essen","","comer","é-sen","Ich esse gern Pizza.","Me gusta comer pizza.","Was isst du?","¿Qué comes?","Wir essen zusammen.","Comemos juntos."],
  ["trinken","","beber","trínk-en","Ich trinke Kaffee.","Bebo café.","Was trinkst du?","¿Qué bebes?","Er trinkt Wasser.","Él bebe agua."],
  ["fahren","","ir (en vehículo) / conducir","fá-ren","Ich fahre mit dem Auto.","Voy en coche.","Fährst du nach Berlin?","¿Vas a Berlín?","Der Zug fährt ab.","El tren sale."],
  ["laufen","","correr / caminar","láu-fen","Ich laufe jeden Morgen.","Corro cada mañana.","Lauf schnell!","¡Corre rápido!","Das Kind läuft.","El niño camina."],
  ["schlafen","","dormir","shlá-fen","Ich schlafe gut.","Duermo bien.","Schläfst du schon?","¿Ya duermes?","Er schläft noch.","Todavía duerme."],
  ["wohnen","","vivir / residir","vó-nen","Ich wohne in Wien.","Vivo en Viena.","Wo wohnst du?","¿Dónde vives?","Sie wohnt allein.","Ella vive sola."],
  ["kochen","","cocinar","kó-jen","Ich koche heute.","Cocino hoy.","Kochst du gern?","¿Te gusta cocinar?","Er kocht sehr gut.","Él cocina muy bien."],
  ["helfen","","ayudar","hél-fen","Kann ich helfen?","¿Puedo ayudar?","Er hilft mir.","Me ayuda.","Hilfst du mir bitte?","¿Me ayudas por favor?"],
  ["bringen","","traer / llevar","bríngen","Bring mir das!","¡Tráeme eso!","Ich bringe dir Kaffee.","Te traigo café.","Er bringt mich nach Hause.","Me lleva a casa."],
  ["öffnen","","abrir","öf-nen","Öffne die Tür bitte.","Abre la puerta por favor.","Der Laden öffnet um 9.","La tienda abre a las 9.","Ich öffne das Fenster.","Abro la ventana."],

  // ── 51-70: Pronombres y palabras funcionales ──────────────────────────────
  ["ich","","yo","ich","Ich bin Olga.","Soy Olga.","Ich komme aus Spanien.","Soy de España.","Ich lerne Deutsch.","Aprendo alemán."],
  ["du","","tú","du","Du bist nett.","Eres amable.","Du lernst schnell.","Aprendes rápido.","Wie heißt du?","¿Cómo te llamas?"],
  ["er","","él","er","Er kommt morgen.","Él viene mañana.","Er ist nett.","Él es amable.","Er wohnt hier.","Él vive aquí."],
  ["sie","","ella / ellas / usted","zi","Sie ist schön.","Ella es guapa.","Sie sind hier.","Ellas están aquí.","Wie heißen Sie?","¿Cómo se llama usted?"],
  ["es","","ello","es","Es regnet.","Llueve.","Es ist kalt.","Hace frío.","Wie geht es dir?","¿Cómo estás?"],
  ["wir","","nosotros","vir","Wir lernen Deutsch.","Aprendemos alemán.","Wir sind Freunde.","Somos amigos.","Wir gehen essen.","Vamos a comer."],
  ["ihr","","vosotros","ir","Kommt ihr mit?","¿Venís?","Ihr seid toll.","Sois geniales.","Was macht ihr?","¿Qué hacéis?"],
  ["und","","y","und","Ich und du.","Tú y yo.","Kaffee und Kuchen.","Café y tarta.","Schön und gut.","Bonito y bueno."],
  ["oder","","o","ó-der","Kaffee oder Tee?","¿Café o té?","Ja oder nein?","¿Sí o no?","Heute oder morgen?","¿Hoy o mañana?"],
  ["aber","","pero","á-ber","Ich will, aber ich kann nicht.","Quiero pero no puedo.","Klein aber fein.","Pequeño pero bueno.","Schön, aber teuer.","Bonito pero caro."],

  ["wenn","","cuando / si","ven","Wenn es regnet, bleibe ich zu Hause.","Cuando llueve me quedo en casa.","Ruf an, wenn du da bist.","Llama cuando llegues.","Wenn du willst.","Si quieres."],
  ["weil","","porque","vail","Ich lerne, weil es Spaß macht.","Aprendo porque es divertido.","Er schläft, weil er müde ist.","Duerme porque está cansado.","Warum? Weil!","¿Por qué? ¡Porque sí!"],
  ["dass","","que (conj.)","das","Ich denke, dass es gut ist.","Creo que es bueno.","Ich weiß, dass du kommst.","Sé que vienes.","Es ist schön, dass du da bist.","Qué bien que estés aquí."],
  ["wie","","cómo / como","vi","Wie heißt du?","¿Cómo te llamas?","Schön wie ein Traum.","Bonito como un sueño.","Wie bitte?","¿Perdón?"],
  ["was","","qué","vas","Was ist das?","¿Qué es eso?","Was machst du?","¿Qué haces?","Was kostet das?","¿Cuánto cuesta?"],
  ["wer","","quién","ver","Wer bist du?","¿Quién eres?","Wer kommt?","¿Quién viene?","Wer hat das gesagt?","¿Quién dijo eso?"],
  ["wo","","dónde","vo","Wo bist du?","¿Dónde estás?","Wo wohnst du?","¿Dónde vives?","Wo ist die Toilette?","¿Dónde está el baño?"],
  ["wann","","cuándo","van","Wann kommst du?","¿Cuándo vienes?","Wann fährt der Zug?","¿Cuándo sale el tren?","Wann ist es fertig?","¿Cuándo está listo?"],
  ["warum","","por qué","va-rum","Warum lernst du Deutsch?","¿Por qué aprendes alemán?","Warum nicht?","¿Por qué no?","Warum bist du traurig?","¿Por qué estás triste?"],
  ["wohin","","adónde","vo-jin","Wohin gehst du?","¿Adónde vas?","Wohin fährt der Bus?","¿Adónde va el autobús?","Wohin reist du?","¿Adónde viajas?"],

  // ── 71-90: Artículos y determinantes ─────────────────────────────────────
  ["der","","el (masc.)","der","Der Mann ist nett.","El hombre es amable.","Der Zug kommt.","El tren llega.","Wo ist der Bahnhof?","¿Dónde está la estación?"],
  ["die","","la / las","di","Die Frau lacht.","La mujer ríe.","Die Kinder spielen.","Los niños juegan.","Wo ist die Toilette?","¿Dónde está el baño?"],
  ["das","","el / lo (neutro)","das","Das ist gut.","Eso es bueno.","Das Kind schläft.","El niño duerme.","Was ist das?","¿Qué es eso?"],
  ["ein","","un / una (masc./neutro)","ain","Ein Mann kommt.","Un hombre viene.","Das ist ein Buch.","Eso es un libro.","Ich habe ein Problem.","Tengo un problema."],
  ["eine","","una (fem.)","áy-ne","Eine Frau lacht.","Una mujer ríe.","Das ist eine Katze.","Eso es un gato.","Ich suche eine Wohnung.","Busco un piso."],
  ["kein","","ningún / no (negación)","kain","Kein Problem.","Ningún problema.","Ich habe kein Geld.","No tengo dinero.","Das ist kein Fehler.","Eso no es un error."],
  ["dieser","","este / esta / esto","dí-zer","Dieser Zug fährt nach Berlin.","Este tren va a Berlín.","Diese Frau ist nett.","Esta mujer es amable.","Dieses Haus ist groß.","Esta casa es grande."],
  ["jeder","","cada / todo","yé-der","Jeden Tag lerne ich.","Cada día aprendo.","Jeder Mensch ist anders.","Cada persona es diferente.","Jeden Morgen Kaffee.","Café cada mañana."],
  ["alle","","todos / todas","á-le","Alle sind hier.","Todos están aquí.","Ich kenne alle.","Conozco a todos.","Nicht alle wissen das.","No todos lo saben."],
  ["viele","","muchos / muchas","fí-le","Viele Leute kommen.","Mucha gente viene.","Ich habe viele Freunde.","Tengo muchos amigos.","Viele Möglichkeiten.","Muchas posibilidades."],

  // ── 91-110: Preposiciones ─────────────────────────────────────────────────
  ["in","","en / dentro de","in","Ich bin in Berlin.","Estoy en Berlín.","Im Winter ist es kalt.","En invierno hace frío.","Sie ist in der Schule.","Está en el colegio."],
  ["an","","en / junto a / pegado a","an","Am Montag arbeite ich.","El lunes trabajo.","Ich bin an der Haltestelle.","Estoy en la parada.","Denk an mich.","Piensa en mí."],
  ["auf","","en / sobre (superficie)","auf","Das Buch liegt auf dem Tisch.","El libro está sobre la mesa.","Auf Deutsch bitte.","En alemán por favor.","Warte auf mich!","¡Espérame!"],
  ["aus","","de / desde / de vuelta","aus","Ich komme aus Spanien.","Soy de España.","Aus welchem Land?","¿De qué país?","Geh raus!","¡Sal fuera!"],
  ["bei","","en casa de / en / cerca de","bay","Ich bin bei dir.","Estoy contigo.","Bei mir zu Hause.","En mi casa.","Bei der Arbeit.","En el trabajo."],
  ["mit","","con","mit","Kommst du mit?","¿Vienes conmigo?","Mit dem Auto.","En coche.","Mit dir macht es Spaß.","Contigo es divertido."],
  ["nach","","hacia / después de / según","naj","Ich fahre nach Berlin.","Voy a Berlín.","Nach dem Essen.","Después de comer.","Nach Hause.","A casa."],
  ["von","","de / desde / por","fon","Ich komme von der Arbeit.","Vengo del trabajo.","Das ist von mir.","Eso es de mi parte.","Von Montag bis Freitag.","De lunes a viernes."],
  ["vor","","delante de / antes de / hace","for","Vor dem Haus.","Delante de la casa.","Vor dem Essen.","Antes de comer.","Vor zwei Jahren.","Hace dos años."],
  ["zu","","a / hacia / demasiado","tsu","Ich gehe zu dir.","Voy a tu casa.","Zu Fuß.","A pie.","Das ist zu viel.","Eso es demasiado."],

  ["für","","para / por","für","Das ist für dich.","Eso es para ti.","Für immer.","Para siempre.","Für mich, bitte.","Para mí, por favor."],
  ["durch","","a través de / por","durj","Durch den Park.","Por el parque.","Durch das Fenster.","Por la ventana.","Ich fahre durch die Stadt.","Conduzco por la ciudad."],
  ["über","","sobre / encima de / acerca de","ü-ber","Wir reden über dich.","Hablamos de ti.","Die Brücke über den Fluss.","El puente sobre el río.","Über alles.","Sobre todo."],
  ["unter","","debajo de / entre","ún-ter","Unter dem Tisch.","Debajo de la mesa.","Unter uns.","Entre nosotros.","Unter Freunden.","Entre amigos."],
  ["zwischen","","entre (dos cosas)","tsvíshen","Zwischen dir und mir.","Entre tú y yo.","Zwischen Montag und Mittwoch.","Entre el lunes y el miércoles.","Zwischen den Stühlen.","Entre las sillas."],
  ["ohne","","sin","ó-ne","Kaffee ohne Milch.","Café sin leche.","Ich kann nicht ohne dich.","No puedo sin ti.","Ohne Geld.","Sin dinero."],
  ["gegen","","contra / hacia (aprox.)","gé-gen","Gegen die Wand.","Contra la pared.","Gegen 8 Uhr.","Hacia las 8.","Ich bin dagegen.","Estoy en contra."],
  ["um","","a las (hora) / alrededor de / para","um","Um 8 Uhr.","A las 8.","Um das Haus herum.","Alrededor de la casa.","Um Hilfe bitten.","Pedir ayuda."],
  ["bis","","hasta","bis","Bis morgen!","¡Hasta mañana!","Bis 5 Uhr.","Hasta las 5.","Bis bald!","¡Hasta pronto!"],
  ["seit","","desde (hace)","zait","Ich lerne seit einem Jahr.","Aprendo desde hace un año.","Seit wann?","¿Desde cuándo?","Seit Montag.","Desde el lunes."],

  // ── 111-130: Adverbios frecuentes ─────────────────────────────────────────
  ["nicht","","no / no (negación verbal)","nijt","Ich verstehe nicht.","No entiendo.","Das ist nicht gut.","Eso no es bueno.","Nicht so laut!","¡No tan alto!"],
  ["auch","","también / igualmente","auj","Ich auch!","¡Yo también!","Das weiß ich auch nicht.","Eso tampoco lo sé.","Auch du.","Tú también."],
  ["noch","","todavía / aún / además","noj","Ich bin noch hier.","Todavía estoy aquí.","Noch ein Bier.","Otra cerveza.","Noch nicht.","Todavía no."],
  ["schon","","ya","shon","Ich bin schon da.","Ya estoy aquí.","Schon wieder?","¿Otra vez?","Das kenne ich schon.","Ya lo conozco."],
  ["nur","","solo / solamente","nur","Ich habe nur 5 Euro.","Solo tengo 5 euros.","Nur du.","Solo tú.","Nur kurz.","Solo un momento."],
  ["immer","","siempre","í-mer","Ich trinke immer Kaffee.","Siempre bebo café.","Das macht er immer so.","Siempre lo hace así.","Für immer.","Para siempre."],
  ["nie","","nunca","ni","Ich habe das nie gesagt.","Nunca dije eso.","Das mache ich nie.","Eso nunca lo hago.","Nie wieder!","¡Nunca más!"],
  ["jetzt","","ahora","yetst","Ich muss jetzt gehen.","Tengo que irme ahora.","Jetzt oder nie.","Ahora o nunca.","Was ist jetzt?","¿Qué pasa ahora?"],
  ["dann","","entonces / luego","dan","Erst lernen, dann spielen.","Primero estudiar, luego jugar.","Bis dann!","¡Hasta entonces!","Was dann?","¿Y luego qué?"],
  ["hier","","aquí","jir","Ich bin hier.","Estoy aquí.","Komm her!","¡Ven aquí!","Hier entlang.","Por aquí."],

  ["dort","","allí / allá","dort","Er ist dort.","Él está allí.","Dort drüben.","Allí enfrente.","Dort kannst du parken.","Allí puedes aparcar."],
  ["da","","ahí / aquí / ya que","da","Da bin ich!","¡Aquí estoy!","Da ist er.","Ahí está él.","Da du das weißt...","Ya que sabes eso..."],
  ["so","","así / tan","zo","So ist das Leben.","Así es la vida.","So schön!","¡Tan bonito!","Mach es so.","Hazlo así."],
  ["sehr","","muy","zér","Das ist sehr gut.","Eso es muy bueno.","Ich bin sehr müde.","Estoy muy cansada.","Sehr gerne!","¡Con mucho gusto!"],
  ["mehr","","más (cantidad)","mér","Ich will mehr.","Quiero más.","Nicht mehr.","Ya no.","Mehr oder weniger.","Más o menos."],
  ["viel","","mucho / muchos","fil","Ich lerne viel.","Aprendo mucho.","Viel Glück!","¡Mucha suerte!","Vielen Dank!","¡Muchas gracias!"],
  ["wenig","","poco / pocos","vé-nig","Ich habe wenig Zeit.","Tengo poco tiempo.","Ein bisschen wenig.","Un poco poco.","Weniger ist mehr.","Menos es más."],
  ["gut","","bien / bueno","gut","Das ist gut.","Eso está bien.","Alles gut?","¿Todo bien?","Gut gemacht!","¡Bien hecho!"],
  ["schlecht","","mal / malo","shlecht","Das ist schlecht.","Eso está mal.","Mir geht es schlecht.","No me encuentro bien.","Schlechtes Wetter.","Mal tiempo."],
  ["vielleicht","","quizás / tal vez","fi-láicht","Vielleicht morgen.","Quizás mañana.","Komm doch vielleicht mit?","¿Quizás te animas a venir?","Ich weiß es nicht, vielleicht.","No lo sé, quizás."],

  // ── 131-160: Tiempo ───────────────────────────────────────────────────────
  ["heute","","hoy","hóy-te","Was machst du heute?","¿Qué haces hoy?","Heute ist Montag.","Hoy es lunes.","Heute Abend.","Esta noche."],
  ["gestern","","ayer","gés-tern","Gestern war schön.","Ayer fue bonito.","Was war gestern?","¿Qué pasó ayer?","Ich habe gestern geschlafen.","Ayer dormí."],
  ["morgen","","mañana (día siguiente)","mór-gen","Bis morgen!","¡Hasta mañana!","Morgen früh.","Mañana por la mañana.","Was machst du morgen?","¿Qué haces mañana?"],
  ["bald","","pronto / enseguida","balt","Bis bald!","¡Hasta pronto!","Ich komme bald.","Vengo pronto.","Bald ist es fertig.","Pronto estará listo."],
  ["früh","","temprano / por la mañana","früh","Ich stehe früh auf.","Me levanto temprano.","Morgen früh.","Mañana por la mañana.","Zu früh.","Demasiado temprano."],
  ["spät","","tarde","shpét","Es ist spät.","Es tarde.","Zu spät!","¡Demasiado tarde!","Ich komme zu spät.","Llego tarde."],
  ["immer noch","","todavía","í-mer noj","Ich bin immer noch hier.","Todavía sigo aquí.","Regnest es immer noch?","¿Todavía llueve?","Er lernt immer noch.","Todavía sigue estudiando."],
  ["der Tag","der","el día","der Tak","Was für ein schöner Tag!","¡Qué día tan bonito!","Guten Tag!","¡Buenos días!","Der Tag ist lang.","El día es largo."],
  ["die Nacht","die","la noche","di Najt","Gute Nacht!","¡Buenas noches!","In der Nacht schlafe ich.","Por la noche duermo.","Die Nacht war lang.","La noche fue larga."],
  ["der Morgen","der","la mañana","der Mór-gen","Guten Morgen!","¡Buenos días!","Am Morgen trinke ich Kaffee.","Por la mañana bebo café.","Jeden Morgen.","Cada mañana."],

  ["der Abend","der","la tarde / la noche","der Á-bent","Guten Abend!","¡Buenas tardes!","Am Abend koche ich.","Por la tarde cocino.","Heute Abend.","Esta tarde / noche."],
  ["das Jahr","das","el año","das Yar","Dieses Jahr lerne ich Deutsch.","Este año aprendo alemán.","Letztes Jahr.","El año pasado.","Nächstes Jahr.","El año que viene."],
  ["der Monat","der","el mes","der Mó-nat","Im nächsten Monat.","El mes que viene.","Welcher Monat ist das?","¿Qué mes es este?","Drei Monate.","Tres meses."],
  ["die Woche","die","la semana","di Vó-je","Diese Woche bin ich beschäftigt.","Esta semana estoy ocupada.","Letzte Woche.","La semana pasada.","Nächste Woche.","La semana que viene."],
  ["die Stunde","die","la hora","di Shtún-de","Eine Stunde Deutsch pro Tag.","Una hora de alemán al día.","In einer Stunde.","En una hora.","Zwei Stunden.","Dos horas."],
  ["die Minute","die","el minuto","di Mi-nú-te","Warte eine Minute!","¡Espera un minuto!","In fünf Minuten.","En cinco minutos.","Das dauert zehn Minuten.","Eso tarda diez minutos."],
  ["der Montag","der","el lunes","der Món-tak","Am Montag arbeite ich.","El lunes trabajo.","Nächsten Montag.","El lunes que viene.","Montag bis Freitag.","De lunes a viernes."],
  ["der Dienstag","der","el martes","der Díns-tak","Dienstag habe ich frei.","El martes tengo libre.","Jeden Dienstag.","Todos los martes.","Am Dienstag.","El martes."],
  ["der Mittwoch","der","el miércoles","der Mít-voj","Mittwoch ist Halbzeit!","¡El miércoles es mitad de semana!","Am Mittwoch.","El miércoles.","Diesen Mittwoch.","Este miércoles."],
  ["der Donnerstag","der","el jueves","der Dó-ners-tak","Am Donnerstag gehe ich ins Kino.","El jueves voy al cine.","Jeden Donnerstag.","Todos los jueves.","Nächsten Donnerstag.","El jueves que viene."],

  ["der Freitag","der","el viernes","der Fráy-tak","Freitag ist mein Lieblingstag.","El viernes es mi día favorito.","Am Freitagabend.","El viernes por la noche.","Nächsten Freitag.","El viernes que viene."],
  ["der Samstag","der","el sábado","der Záms-tak","Am Samstag schlafe ich lange.","El sábado duermo hasta tarde.","Jeden Samstag.","Todos los sábados.","Diesen Samstag.","Este sábado."],
  ["der Sonntag","der","el domingo","der Zón-tak","Am Sonntag bin ich zu Hause.","El domingo estoy en casa.","Jeden Sonntag.","Todos los domingos.","Nächsten Sonntag.","El domingo que viene."],
  ["der Frühling","der","la primavera","der Früh-ling","Im Frühling blühen die Blumen.","En primavera florecen las flores.","Der Frühling beginnt.","Empieza la primavera.","Ein warmer Frühling.","Una primavera cálida."],
  ["der Sommer","der","el verano","der Zó-mer","Im Sommer fahre ich ans Meer.","En verano voy al mar.","Ein heißer Sommer.","Un verano caluroso.","Diesen Sommer.","Este verano."],
  ["der Herbst","der","el otoño","der Herbst","Im Herbst fallen die Blätter.","En otoño caen las hojas.","Ein bunter Herbst.","Un otoño colorido.","Letzten Herbst.","El otoño pasado."],
  ["der Winter","der","el invierno","der Vín-ter","Im Winter schneit es.","En invierno nieva.","Ein kalter Winter.","Un invierno frío.","Diesen Winter.","Este invierno."],
  ["die Uhr","die","el reloj / en punto","di Ur","Wie viel Uhr ist es?","¿Qué hora es?","Um 8 Uhr.","A las 8.","Die Uhr geht nach.","El reloj va atrasado."],
  ["halb","","media (hora)","halp","Halb acht.","Las siete y media.","In einer halben Stunde.","En media hora.","Um halb neun.","A las ocho y media."],
  ["jetzt gerade","","ahora mismo","yetst ge-rá-de","Was machst du jetzt gerade?","¿Qué estás haciendo ahora mismo?","Ich bin gerade beschäftigt.","Ahora mismo estoy ocupada.","Er kommt gerade.","Acaba de llegar."],

  // ── 161-200: Personas y familia ───────────────────────────────────────────
  ["der Mann","der","el hombre / el marido","der Man","Der Mann lacht.","El hombre ríe.","Mein Mann.","Mi marido.","Ein netter Mann.","Un hombre amable."],
  ["die Frau","die","la mujer / la señora / la esposa","di Frau","Die Frau arbeitet.","La mujer trabaja.","Meine Frau.","Mi esposa.","Guten Tag, Frau Müller.","Buenos días, señora Müller."],
  ["das Kind","das","el niño / el hijo","das Kind","Das Kind spielt.","El niño juega.","Mein Kind.","Mi hijo.","Wie alt ist das Kind?","¿Cuántos años tiene el niño?"],
  ["die Familie","die","la familia","di Fa-mí-lie","Meine Familie ist groß.","Mi familia es grande.","Wie geht es der Familie?","¿Cómo está la familia?","Familie ist wichtig.","La familia es importante."],
  ["die Mutter","die","la madre","di Mú-ter","Meine Mutter kocht gut.","Mi madre cocina bien.","Wo ist deine Mutter?","¿Dónde está tu madre?","Sie ist wie eine Mutter.","Es como una madre."],
  ["der Vater","der","el padre","der Fá-ter","Mein Vater arbeitet viel.","Mi padre trabaja mucho.","Wie ist dein Vater?","¿Cómo es tu padre?","Vater und Mutter.","Padre y madre."],
  ["die Eltern","","los padres (siempre plural)","di él-tern","Meine Eltern wohnen in Wien.","Mis padres viven en Viena.","Wie sind deine Eltern?","¿Cómo son tus padres?","Meine Eltern sind nett.","Mis padres son amables."],
  ["die Schwester","die","la hermana","di Shvés-ter","Ich habe eine Schwester.","Tengo una hermana.","Meine große Schwester.","Mi hermana mayor.","Sie ist wie eine Schwester.","Es como una hermana."],
  ["der Bruder","der","el hermano","der Brú-der","Mein Bruder wohnt in Berlin.","Mi hermano vive en Berlín.","Hast du einen Bruder?","¿Tienes un hermano?","Mein kleiner Bruder.","Mi hermano pequeño."],
  ["der Freund","der","el amigo / el novio","der Froynd","Das ist mein Freund.","Este es mi amigo.","Mein Freund kommt.","Mi novio viene.","Ich habe viele Freunde.","Tengo muchos amigos."],

  ["die Freundin","die","la amiga / la novia","di Fróyn-din","Das ist meine Freundin.","Esta es mi amiga.","Meine beste Freundin.","Mi mejor amiga.","Sie ist meine Freundin.","Es mi novia."],
  ["der Mensch","der","la persona / el ser humano","der Mensh","Was für ein netter Mensch!","¡Qué persona tan amable!","Alle Menschen sind gleich.","Todos los seres humanos son iguales.","Der Mensch ist interessant.","El ser humano es interesante."],
  ["die Leute","","la gente (siempre plural)","di Lóy-te","Viele Leute kommen.","Mucha gente viene.","Die Leute sind nett.","La gente es amable.","Was sagen die Leute?","¿Qué dice la gente?"],
  ["der Junge","der","el chico / el niño","der Yún-ge","Der Junge spielt Fußball.","El chico juega al fútbol.","Ein kleiner Junge.","Un niño pequeño.","Wie alt ist der Junge?","¿Cuántos años tiene el chico?"],
  ["das Mädchen","das","la chica / la niña","das Mét-jen","Das Mädchen singt.","La chica canta.","Ein kleines Mädchen.","Una niña pequeña.","Das Mädchen lacht.","La chica ríe."],
  ["der Kollege","der","el compañero de trabajo","der Ko-lé-ge","Mein Kollege ist nett.","Mi compañero es amable.","Die Kollegen kommen.","Los compañeros vienen.","Ein guter Kollege.","Un buen compañero."],
  ["der Chef","der","el jefe","der Shef","Mein Chef ist streng.","Mi jefe es estricto.","Der Chef ruft an.","El jefe llama.","Sprich mit dem Chef.","Habla con el jefe."],
  ["der Arzt","der","el médico","der Artst","Ich gehe zum Arzt.","Voy al médico.","Der Arzt hilft mir.","El médico me ayuda.","Ein guter Arzt.","Un buen médico."],
  ["der Nachbar","der","el vecino","der Náj-bar","Mein Nachbar ist nett.","Mi vecino es amable.","Die Nachbarn feiern.","Los vecinos celebran.","Wie heißt dein Nachbar?","¿Cómo se llama tu vecino?"],
  ["der Gast","der","el invitado / el huésped","der Gast","Wir haben Gäste.","Tenemos invitados.","Der Gast kommt um 8.","El invitado viene a las 8.","Sei mein Gast!","¡Sé mi invitado!"],

  // ── 201-240: Casa y hogar ─────────────────────────────────────────────────
  ["das Haus","das","la casa","das Haus","Ich bin zu Hause.","Estoy en casa.","Das Haus ist groß.","La casa es grande.","Nach Hause gehen.","Ir a casa."],
  ["die Wohnung","die","el piso / el apartamento","di Vó-nung","Ich suche eine Wohnung.","Busco un piso.","Meine Wohnung ist klein.","Mi piso es pequeño.","Eine schöne Wohnung.","Un piso bonito."],
  ["das Zimmer","das","la habitación / el cuarto","das Tsí-mer","Mein Zimmer ist ordentlich.","Mi habitación está ordenada.","Ein helles Zimmer.","Una habitación luminosa.","Das Zimmer ist frei.","La habitación está libre."],
  ["die Küche","die","la cocina","di Küj-e","Die Küche ist modern.","La cocina es moderna.","Ich koche in der Küche.","Cocino en la cocina.","Eine kleine Küche.","Una cocina pequeña."],
  ["das Badezimmer","das","el cuarto de baño","das Bá-de-tsí-mer","Das Badezimmer ist links.","El baño está a la izquierda.","Ich bin im Badezimmer.","Estoy en el baño.","Ein sauberes Badezimmer.","Un baño limpio."],
  ["das Wohnzimmer","das","el salón / la sala de estar","das Vón-tsí-mer","Wir sitzen im Wohnzimmer.","Estamos en el salón.","Das Wohnzimmer ist groß.","El salón es grande.","Im Wohnzimmer fernsehen.","Ver la tele en el salón."],
  ["das Schlafzimmer","das","el dormitorio","das Shlaf-tsí-mer","Mein Schlafzimmer ist ruhig.","Mi dormitorio es tranquilo.","Im Schlafzimmer schlafen.","Dormir en el dormitorio.","Ein kleines Schlafzimmer.","Un dormitorio pequeño."],
  ["die Tür","die","la puerta","di Tür","Mach die Tür auf!","¡Abre la puerta!","Die Tür ist offen.","La puerta está abierta.","Klopf an die Tür.","Llama a la puerta."],
  ["das Fenster","das","la ventana","das Féns-ter","Das Fenster ist offen.","La ventana está abierta.","Schau aus dem Fenster.","Mira por la ventana.","Mach das Fenster zu.","Cierra la ventana."],
  ["der Tisch","der","la mesa","der Tish","Das liegt auf dem Tisch.","Eso está en la mesa.","Setz dich an den Tisch.","Siéntate a la mesa.","Ein runder Tisch.","Una mesa redonda."],

  ["der Stuhl","der","la silla","der Shtul","Setz dich auf den Stuhl.","Siéntate en la silla.","Ein bequemer Stuhl.","Una silla cómoda.","Der Stuhl ist kaputt.","La silla está rota."],
  ["das Bett","das","la cama","das Bet","Ich gehe ins Bett.","Me voy a la cama.","Das Bett ist bequem.","La cama es cómoda.","Im Bett bleiben.","Quedarse en la cama."],
  ["der Schrank","der","el armario","der Shrank","Meine Kleider sind im Schrank.","Mi ropa está en el armario.","Ein großer Schrank.","Un armario grande.","Im Schrank suchen.","Buscar en el armario."],
  ["das Sofa","das","el sofá","das Zó-fa","Ich sitze auf dem Sofa.","Estoy sentada en el sofá.","Ein bequemes Sofa.","Un sofá cómodo.","Wir sitzen auf dem Sofa.","Estamos en el sofá."],
  ["die Lampe","die","la lámpara","di Lám-pe","Mach die Lampe an!","¡Enciende la lámpara!","Eine helle Lampe.","Una lámpara brillante.","Die Lampe ist kaputt.","La lámpara está rota."],
  ["der Kühlschrank","der","el frigorífico","der Kühl-shrank","Was ist im Kühlschrank?","¿Qué hay en el frigorífico?","Der Kühlschrank ist leer.","El frigorífico está vacío.","Stell das in den Kühlschrank.","Ponlo en el frigorífico."],
  ["der Schlüssel","der","la llave","der Shlü-sel","Wo ist mein Schlüssel?","¿Dónde está mi llave?","Ich habe den Schlüssel vergessen.","Olvidé la llave.","Den Schlüssel verlieren.","Perder la llave."],
  ["der Strom","der","la electricidad / la corriente","der Shtrom","Der Strom ist weg.","Se ha ido la luz.","Strom sparen.","Ahorrar electricidad.","Kein Strom.","Sin luz."],
  ["das Wasser","das","el agua","das Vá-ser","Ich trinke Wasser.","Bebo agua.","Heiß oder kalt? — Das Wasser.","¿Caliente o frío? — El agua.","Viel Wasser trinken.","Beber mucha agua."],
  ["die Miete","die","el alquiler","di Mí-te","Die Miete ist teuer.","El alquiler es caro.","Miete zahlen.","Pagar el alquiler.","Wie hoch ist die Miete?","¿Cuánto es el alquiler?"],

  // ── 241-280: Ciudad y transporte ─────────────────────────────────────────
  ["die Stadt","die","la ciudad","di Shtat","Ich lebe in der Stadt.","Vivo en la ciudad.","Eine große Stadt.","Una ciudad grande.","In der Stadt unterwegs.","Por la ciudad."],
  ["das Land","das","el país / el campo","das Lant","Aus welchem Land bist du?","¿De qué país eres?","Auf dem Land leben.","Vivir en el campo.","Ein schönes Land.","Un país bonito."],
  ["die Straße","die","la calle","di Shtrá-se","In welcher Straße wohnst du?","¿En qué calle vives?","Die Straße entlang.","Por la calle.","Eine belebte Straße.","Una calle animada."],
  ["der Weg","der","el camino / la ruta","der Vek","Zeig mir den Weg!","¡Muéstrame el camino!","Der kürzeste Weg.","El camino más corto.","Ich bin auf dem Weg.","Estoy de camino."],
  ["der Platz","der","la plaza / el sitio","der Plats","Ist hier noch ein Platz frei?","¿Hay algún sitio libre aquí?","Der Marktplatz.","La plaza del mercado.","Kein Platz mehr.","Ya no hay sitio."],
  ["der Park","der","el parque","der Park","Ich gehe in den Park.","Voy al parque.","Im Park spazieren.","Pasear por el parque.","Ein schöner Park.","Un parque bonito."],
  ["der Bahnhof","der","la estación de tren","der Ban-jof","Wo ist der Bahnhof?","¿Dónde está la estación?","Am Bahnhof treffen.","Quedar en la estación.","Der Hauptbahnhof.","La estación central."],
  ["der Flughafen","der","el aeropuerto","der Fluk-já-fen","Ich bin am Flughafen.","Estoy en el aeropuerto.","Den Flughafen erreichen.","Llegar al aeropuerto.","Flughafen Berlin.","Aeropuerto de Berlín."],
  ["das Auto","das","el coche","das Au-to","Ich fahre mit dem Auto.","Voy en coche.","Hast du ein Auto?","¿Tienes coche?","Das Auto ist kaputt.","El coche está averiado."],
  ["der Bus","der","el autobús","der Bus","Ich nehme den Bus.","Cojo el autobús.","Wann kommt der Bus?","¿Cuándo viene el autobús?","Den Bus verpassen.","Perder el autobús."],

  ["der Zug","der","el tren","der Tsuk","Der Zug fährt ab.","El tren sale.","Mit dem Zug fahren.","Ir en tren.","Den Zug nehmen.","Coger el tren."],
  ["die U-Bahn","die","el metro","di U-Ban","Ich fahre mit der U-Bahn.","Voy en metro.","Die U-Bahn kommt.","Llega el metro.","U-Bahn-Ticket kaufen.","Comprar ticket de metro."],
  ["das Fahrrad","das","la bicicleta","das Fár-rat","Ich fahre Fahrrad.","Voy en bici.","Das Fahrrad abstellen.","Aparcar la bici.","Mit dem Fahrrad zur Arbeit.","Al trabajo en bici."],
  ["das Taxi","das","el taxi","das Tá-xi","Ich nehme ein Taxi.","Cojo un taxi.","Taxi rufen.","Llamar a un taxi.","Das Taxi kommt.","Llega el taxi."],
  ["die Haltestelle","die","la parada (de bus/tranvía)","di Hál-te-shte-le","Wo ist die nächste Haltestelle?","¿Dónde está la próxima parada?","An der Haltestelle warten.","Esperar en la parada.","Die Haltestelle ist nah.","La parada está cerca."],
  ["die Brücke","die","el puente","di Brü-ke","Über die Brücke gehen.","Cruzar el puente.","Eine alte Brücke.","Un puente antiguo.","Die Brücke ist lang.","El puente es largo."],
  ["links","","a la izquierda","links","Links abbiegen.","Girar a la izquierda.","Das ist links.","Eso está a la izquierda.","Links von hier.","A la izquierda de aquí."],
  ["rechts","","a la derecha","rejts","Rechts abbiegen.","Girar a la derecha.","Das ist rechts.","Eso está a la derecha.","Nach rechts gehen.","Ir hacia la derecha."],
  ["geradeaus","","todo recto","ge-rá-de-aus","Gehen Sie geradeaus.","Vaya todo recto.","Immer geradeaus.","Siempre recto.","Hier geradeaus.","Aquí todo recto."],
  ["nah","","cerca","na","Das ist nah.","Eso está cerca.","Ganz nah.","Muy cerca.","Nah am Bahnhof.","Cerca de la estación."],

  // ── 281-320: Comida y bebida ──────────────────────────────────────────────
  ["das Essen","das","la comida / la cesta","das É-sen","Das Essen ist lecker.","La comida está rica.","Was gibt es zum Essen?","¿Qué hay para comer?","Essen gehen.","Salir a comer."],
  ["das Brot","das","el pan","das Brot","Ich esse Brot zum Frühstück.","Como pan en el desayuno.","Frisches Brot.","Pan fresco.","Ein Stück Brot.","Un trozo de pan."],
  ["der Käse","der","el queso","der Ké-ze","Ich esse Brot mit Käse.","Como pan con queso.","Ein Stück Käse.","Un trozo de queso.","Welcher Käse ist das?","¿Qué queso es este?"],
  ["das Fleisch","das","la carne","das Flaish","Ich esse kein Fleisch.","No como carne.","Frisches Fleisch.","Carne fresca.","Welches Fleisch magst du?","¿Qué carne te gusta?"],
  ["das Gemüse","das","la verdura","das Ge-mü-ze","Ich esse gern Gemüse.","Me gustan las verduras.","Frisches Gemüse.","Verdura fresca.","Viel Gemüse essen.","Comer mucha verdura."],
  ["das Obst","das","la fruta","das Opst","Ich esse jeden Tag Obst.","Como fruta cada día.","Frisches Obst.","Fruta fresca.","Welches Obst magst du?","¿Qué fruta te gusta?"],
  ["die Milch","die","la leche","di Milj","Kaffee mit Milch.","Café con leche.","Ein Glas Milch.","Un vaso de leche.","Die Milch ist kalt.","La leche está fría."],
  ["das Ei","das","el huevo","das Ai","Ich esse Eier zum Frühstück.","Como huevos en el desayuno.","Ein gekochtes Ei.","Un huevo cocido.","Zwei Eier, bitte.","Dos huevos, por favor."],
  ["der Kaffee","der","el café","der Ká-fe","Ich trinke gern Kaffee.","Me gusta el café.","Einen Kaffee bitte.","Un café por favor.","Kaffee mit Milch.","Café con leche."],
  ["der Tee","der","el té","der Té","Ich trinke Tee.","Bebo té.","Ein Tee ohne Zucker.","Un té sin azúcar.","Grüner Tee.","Té verde."],

  ["das Bier","das","la cerveza","das Bir","Ein Bier bitte!","¡Una cerveza por favor!","Deutsches Bier ist gut.","La cerveza alemana es buena.","Ich trinke gern Bier.","Me gusta la cerveza."],
  ["der Wein","der","el vino","der Vain","Ein Glas Wein bitte.","Una copa de vino por favor.","Roter oder weißer Wein?","¿Vino tinto o blanco?","Ich mag Wein.","Me gusta el vino."],
  ["das Wasser","das","el agua","das Vá-ser","Ein Wasser bitte.","Un agua por favor.","Stilles oder mit Gas?","¿Sin gas o con gas?","Viel Wasser trinken.","Beber mucha agua."],
  ["der Saft","der","el zumo / el jugo","der Zaft","Ein Glas Saft bitte.","Un vaso de zumo por favor.","Orangensaft.","Zumo de naranja.","Frischer Saft.","Zumo natural."],
  ["der Kuchen","der","el pastel / la tarta","der Kú-jen","Der Kuchen ist lecker.","El pastel está rico.","Ein Stück Kuchen.","Un trozo de tarta.","Kaffee und Kuchen.","Café y tarta."],
  ["das Frühstück","das","el desayuno","das Früh-shtük","Was gibt es zum Frühstück?","¿Qué hay para desayunar?","Ich frühstücke um 8.","Desayuno a las 8.","Ein gutes Frühstück.","Un buen desayuno."],
  ["das Mittagessen","das","el almuerzo","das Mí-tak-é-sen","Das Mittagessen um 12.","El almuerzo a las 12.","Was gibt es zum Mittagessen?","¿Qué hay para comer?","Mittagessen machen.","Preparar el almuerzo."],
  ["das Abendessen","das","la cena","das Á-bent-é-sen","Das Abendessen um 19 Uhr.","La cena a las 19.","Was gibt es zum Abendessen?","¿Qué hay para cenar?","Abendessen kochen.","Cocinar la cena."],
  ["der Zucker","der","el azúcar","der Tsú-ker","Mit oder ohne Zucker?","¿Con o sin azúcar?","Kein Zucker bitte.","Sin azúcar por favor.","Zu viel Zucker.","Demasiado azúcar."],
  ["das Salz","das","la sal","das Zalts","Das braucht mehr Salz.","Eso necesita más sal.","Salz und Pfeffer.","Sal y pimienta.","Kein Salz bitte.","Sin sal por favor."],

  // ── 321-360: Adjetivos descriptivos ──────────────────────────────────────
  ["groß","","grande / alto","gros","Das Haus ist groß.","La casa es grande.","Er ist groß.","Él es alto.","Wie groß bist du?","¿Cuánto mides?"],
  ["klein","","pequeño / bajo","klayn","Das Zimmer ist klein.","La habitación es pequeña.","Eine kleine Katze.","Un gato pequeño.","Ich bin klein.","Soy bajita."],
  ["schön","","bonito / guapo / agradable","shön","Das ist sehr schön!","¡Eso es muy bonito!","Schönes Wetter heute.","Buen tiempo hoy.","Du bist schön.","Eres guapa."],
  ["hässlich","","feo","hés-lij","Das ist hässlich.","Eso es feo.","Ein hässliches Wort.","Una palabra fea.","Warum so hässlich?","¿Por qué tan feo?"],
  ["neu","","nuevo","noy","Das ist neu.","Eso es nuevo.","Ein neues Handy.","Un móvil nuevo.","Etwas Neues.","Algo nuevo."],
  ["alt","","viejo / antiguo / mayor","alt","Das Haus ist alt.","La casa es vieja.","Wie alt bist du?","¿Cuántos años tienes?","Ein altes Buch.","Un libro viejo."],
  ["jung","","joven","yung","Sie ist jung.","Ella es joven.","Für immer jung.","Siempre jóvenes.","Ein junges Team.","Un equipo joven."],
  ["lang","","largo / mucho tiempo","lang","Das dauert lang.","Eso tarda mucho.","Eine lange Straße.","Una calle larga.","Wie lang ist das?","¿Cuánto mide eso?"],
  ["kurz","","corto / breve","kurts","Das ist kurz.","Eso es corto.","Eine kurze Pause.","Una pausa breve.","Kurz und gut.","Breve y bueno."],
  ["schnell","","rápido / deprisa","shnel","Fahr nicht so schnell!","¡No conduzcas tan rápido!","Sehr schnell lernen.","Aprender muy rápido.","Das geht schnell.","Eso va rápido."],

  ["langsam","","lento / despacio","lán-zam","Sprich bitte langsamer!","¡Habla más despacio por favor!","Ein langsamer Zug.","Un tren lento.","Langsam aber sicher.","Despacio pero seguro."],
  ["laut","","alto / ruidoso","laut","Nicht so laut bitte.","No tan alto por favor.","Die Musik ist zu laut.","La música está muy alta.","Ein lautes Auto.","Un coche ruidoso."],
  ["leise","","suave / silencioso","láy-ze","Sprich leise!","¡Habla bajito!","Sei leise!","¡Estate quieto!","Eine leise Stimme.","Una voz suave."],
  ["warm","","caliente / cálido","varm","Das Wasser ist warm.","El agua está caliente.","Ein warmer Tag.","Un día cálido.","Mir ist warm.","Tengo calor."],
  ["kalt","","frío","kalt","Das Wetter ist kalt.","El tiempo está frío.","Ein kaltes Bier.","Una cerveza fría.","Mir ist kalt.","Tengo frío."],
  ["heiß","","muy caliente / caluroso","hais","Es ist heiß.","Hace mucho calor.","Heißes Wasser.","Agua caliente.","Heute ist es heiß.","Hoy hace calor."],
  ["billig","","barato","bí-lig","Das ist billig.","Eso es barato.","Billige Miete.","Alquiler barato.","Sehr billig kaufen.","Comprar muy barato."],
  ["teuer","","caro","tóy-er","Das ist zu teuer.","Eso es demasiado caro.","Ein teures Restaurant.","Un restaurante caro.","Warum so teuer?","¿Por qué tan caro?"],
  ["lecker","","rico / delicioso","lé-ker","Das ist lecker!","¡Eso está rico!","Sehr lecker.","Muy rico.","Das schmeckt lecker.","Eso sabe rico."],
  ["wichtig","","importante","víj-tig","Das ist sehr wichtig.","Eso es muy importante.","Eine wichtige Frage.","Una pregunta importante.","Was ist dir wichtig?","¿Qué es importante para ti?"],

  // ── 361-400: Salud, cuerpo y estados ─────────────────────────────────────
  ["müde","","cansado","müh-de","Ich bin sehr müde.","Estoy muy cansada.","Du siehst müde aus.","Pareces cansada.","Nicht so müde sein.","No estar tan cansada."],
  ["krank","","enfermo","krank","Ich bin krank.","Estoy enferma.","Bleib zu Hause, du bist krank.","Quédate en casa, estás enferma.","Der Patient ist krank.","El paciente está enfermo."],
  ["gesund","","sano / saludable","ge-zunt","Ich bin gesund.","Estoy sana.","Leb gesund!","¡Vive de forma saludable!","Gesundes Essen.","Comida sana."],
  ["glücklich","","feliz","glük-lij","Ich bin sehr glücklich.","Soy muy feliz.","Du machst mich glücklich.","Me haces feliz.","Glücklich sein.","Ser feliz."],
  ["traurig","","triste","tráu-rig","Ich bin traurig.","Estoy triste.","Warum bist du traurig?","¿Por qué estás triste?","Ein trauriger Film.","Una película triste."],
  ["der Kopf","der","la cabeza","der Kopf","Ich habe Kopfschmerzen.","Me duele la cabeza.","Der Kopf tut weh.","La cabeza me duele.","Kopf hoch!","¡Ánimo! (lit: Cabeza arriba)"],
  ["die Hand","die","la mano","di Hant","Gib mir die Hand.","Dame la mano.","Meine Hände sind kalt.","Mis manos están frías.","Hände waschen.","Lavarse las manos."],
  ["der Arm","der","el brazo","der Arm","Mein Arm tut weh.","Me duele el brazo.","Den Arm brechen.","Romperse el brazo.","Lange Arme.","Brazos largos."],
  ["das Bein","das","la pierna","das Bain","Mein Bein tut weh.","Me duele la pierna.","Ein gebrochenes Bein.","Una pierna rota.","Die Beine sind müde.","Las piernas están cansadas."],
  ["der Bauch","der","el estómago / la barriga","der Bauj","Ich habe Bauchschmerzen.","Me duele el estómago.","Ein voller Bauch.","Una barriga llena.","Mein Bauch tut weh.","Me duele la barriga."],

  ["das Herz","das","el corazón","das Herts","Mein Herz schlägt schnell.","Mi corazón late rápido.","Von Herzen.","De corazón.","Das Herz ist das Wichtigste.","El corazón es lo más importante."],
  ["das Auge","das","el ojo","das Áu-ge","Ich habe blaue Augen.","Tengo ojos azules.","Das Auge tut weh.","Me duele el ojo.","Schöne Augen.","Ojos bonitos."],
  ["der Mund","der","la boca","der Mund","Mach den Mund auf!","¡Abre la boca!","Der Mund ist trocken.","La boca está seca.","Einen Kuss auf den Mund.","Un beso en la boca."],
  ["die Nase","die","la nariz","di Ná-ze","Meine Nase ist verstopft.","Tengo la nariz taponada.","Eine rote Nase.","Una nariz roja.","Die Nase läuft.","La nariz gotea."],
  ["das Ohr","das","la oreja / el oído","das Or","Mein Ohr tut weh.","Me duele el oído.","Laute Musik in den Ohren.","Música alta en los oídos.","Sprich laut, ich höre schlecht.","Habla fuerte, oigo mal."],
  ["der Schmerz","der","el dolor","der Shmerts","Ich habe Schmerzen.","Tengo dolor.","Die Schmerzen sind stark.","El dolor es fuerte.","Gegen den Schmerz.","Contra el dolor."],
  ["die Erkältung","die","el resfriado","di Er-kél-tung","Ich habe eine Erkältung.","Tengo un resfriado.","Eine Erkältung bekommen.","Coger un resfriado.","Die Erkältung geht weg.","El resfriado se va."],
  ["das Fieber","das","la fiebre","das Fí-ber","Ich habe Fieber.","Tengo fiebre.","Hohes Fieber.","Fiebre alta.","Das Fieber sinkt.","La fiebre baja."],
  ["die Apotheke","die","la farmacia","di A-po-té-ke","Ich gehe zur Apotheke.","Voy a la farmacia.","Die Apotheke ist offen.","La farmacia está abierta.","Ein Medikament aus der Apotheke.","Un medicamento de la farmacia."],
  ["das Krankenhaus","das","el hospital","das Krán-ken-haus","Ich muss ins Krankenhaus.","Tengo que ir al hospital.","Im Krankenhaus arbeiten.","Trabajar en el hospital.","Das Krankenhaus ist nah.","El hospital está cerca."],

  // ── 401-430: Trabajo, dinero y compras ───────────────────────────────────
  ["die Arbeit","die","el trabajo","di Ár-bait","Ich gehe zur Arbeit.","Voy al trabajo.","Die Arbeit macht Spaß.","El trabajo es divertido.","Nach der Arbeit.","Después del trabajo."],
  ["das Büro","das","la oficina","das Bü-ro","Ich arbeite im Büro.","Trabajo en la oficina.","Das Büro ist modern.","La oficina es moderna.","Im Büro bleiben.","Quedarse en la oficina."],
  ["die Firma","die","la empresa","di Fír-ma","Ich arbeite in einer Firma.","Trabajo en una empresa.","Eine große Firma.","Una empresa grande.","Für welche Firma?","¿Para qué empresa?"],
  ["das Geld","das","el dinero","das Gelt","Ich habe kein Geld.","No tengo dinero.","Geld ausgeben.","Gastar dinero.","Viel Geld.","Mucho dinero."],
  ["der Euro","der","el euro","der Óy-ro","Das kostet 10 Euro.","Eso cuesta 10 euros.","Wie viel Euro hast du?","¿Cuántos euros tienes?","Einen Euro wechseln.","Cambiar un euro."],
  ["der Preis","der","el precio","der Prais","Was ist der Preis?","¿Cuál es el precio?","Der Preis ist okay.","El precio está bien.","Guter Preis.","Buen precio."],
  ["bezahlen","","pagar","be-tsá-len","Ich möchte bitte bezahlen.","Quisiera pagar por favor.","Wie möchten Sie bezahlen?","¿Cómo quiere pagar?","Mit Karte bezahlen.","Pagar con tarjeta."],
  ["kaufen","","comprar","káu-fen","Was kaufst du?","¿Qué compras?","Ich kaufe ein neues Handy.","Compro un móvil nuevo.","Billig kaufen.","Comprar barato."],
  ["verkaufen","","vender","fer-káu-fen","Ich verkaufe mein Auto.","Vendo mi coche.","Das wird gut verkauft.","Eso se vende bien.","Teuer verkaufen.","Vender caro."],
  ["das Geschäft","das","la tienda / el negocio","das Ge-sheft","Das Geschäft ist offen.","La tienda está abierta.","Ein gutes Geschäft.","Un buen negocio.","Ins Geschäft gehen.","Ir a la tienda."],

  ["der Supermarkt","der","el supermercado","der Zú-per-markt","Ich gehe in den Supermarkt.","Voy al supermercado.","Im Supermarkt einkaufen.","Hacer la compra en el supermercado.","Der Supermarkt ist um die Ecke.","El supermercado está a la vuelta."],
  ["die Kasse","die","la caja (registradora)","di Ká-se","Ich stehe an der Kasse.","Estoy en la caja.","An die Kasse bitte.","A caja por favor.","Die Kasse ist besetzt.","La caja está ocupada."],
  ["die Quittung","die","el recibo / el tíquet","di Kví-tung","Kann ich eine Quittung haben?","¿Me puede dar un recibo?","Die Quittung bitte.","El recibo por favor.","Ich brauche die Quittung.","Necesito el recibo."],
  ["die Kreditkarte","die","la tarjeta de crédito","di Kre-dít-kar-te","Zahlen Sie mit Kreditkarte?","¿Paga con tarjeta?","Kreditkarte akzeptiert.","Se acepta tarjeta.","Ich zahle mit Kreditkarte.","Pago con tarjeta."],
  ["bar","","en efectivo","bar","Ich zahle bar.","Pago en efectivo.","Nur bar.","Solo efectivo.","Hast du Bargeld?","¿Tienes efectivo?"],
  ["das Trinkgeld","das","la propina","das Trínk-gelt","Trinkgeld geben.","Dar propina.","Wie viel Trinkgeld?","¿Cuánto de propina?","Das Trinkgeld ist üblich.","La propina es habitual."],
  ["der Rabatt","der","el descuento","der Ra-bát","Gibt es einen Rabatt?","¿Hay descuento?","10% Rabatt.","10% de descuento.","Mit Rabatt kaufen.","Comprar con descuento."],
  ["das Angebot","das","la oferta","das Án-ge-bot","Das ist ein gutes Angebot.","Es una buena oferta.","Im Angebot.","En oferta.","Das Angebot ist gültig bis Sonntag.","La oferta es válida hasta el domingo."],
  ["kostenlos","","gratuito / gratis","kós-ten-los","Das ist kostenlos.","Es gratis.","Kostenloser Eintritt.","Entrada gratuita.","Ist das kostenlos?","¿Es gratis?"],
  ["die Öffnungszeiten","","el horario (de apertura)","di Öf-nungs-tsai-ten","Was sind die Öffnungszeiten?","¿Cuál es el horario?","Die Öffnungszeiten stehen draußen.","El horario está fuera.","Lange Öffnungszeiten.","Horario amplio."],

  // ── 431-470: Comunicación y expresiones sociales ──────────────────────────
  ["hallo","","hola","há-lo","Hallo! Wie geht's?","¡Hola! ¿Cómo estás?","Hallo zusammen!","¡Hola a todos!","Sag Hallo!","¡Di hola!"],
  ["tschüss","","adiós (informal)","chüs","Tschüss! Bis morgen!","¡Adiós! ¡Hasta mañana!","Tschüss und gute Nacht!","¡Adiós y buenas noches!","Mach's gut, tschüss!","¡Cuídate, adiós!"],
  ["auf Wiedersehen","","hasta la vista (formal)","auf Ví-der-zén","Auf Wiedersehen, Herr Müller.","Hasta la vista, señor Müller.","Auf Wiedersehen bis nächste Woche.","Hasta la vista la semana que viene.","Auf Wiedersehen und danke!","¡Hasta la vista y gracias!"],
  ["bitte","","por favor / de nada","bí-te","Ein Kaffee, bitte.","Un café, por favor.","Bitte schön!","¡De nada!","Wie bitte?","¿Perdón?"],
  ["danke","","gracias","dán-ke","Vielen Dank!","¡Muchas gracias!","Danke sehr!","¡Muchas gracias!","Danke, das ist nett.","Gracias, es muy amable."],
  ["entschuldigung","","disculpa / perdona","ent-shúl-di-gung","Entschuldigung, wo ist der Bahnhof?","Disculpe, ¿dónde está la estación?","Oh, Entschuldigung!","¡Oh, perdona!","Entschuldigung bitte.","Perdona por favor."],
  ["es tut mir leid","","lo siento","es tut mir lait","Es tut mir leid!","¡Lo siento!","Es tut mir wirklich leid.","Lo siento de verdad.","Kein Problem, kein Stress.","No hay problema."],
  ["gern","","con gusto / me gusta","gern","Sehr gern!","¡Con mucho gusto!","Ich esse gern Pizza.","Me gusta comer pizza.","Das mache ich gern.","Eso lo hago con gusto."],
  ["natürlich","","claro / por supuesto / naturalmente","na-tür-lij","Natürlich!","¡Por supuesto!","Das ist natürlich so.","Por supuesto que es así.","Natürlich komme ich.","Claro que vengo."],
  ["klar","","claro / por supuesto","klar","Klar!","¡Claro!","Alles klar?","¿Todo claro?","Ist das klar?","¿Está claro?"],

  ["ja","","sí","ya","Ja, natürlich!","¡Sí, por supuesto!","Ja oder nein?","¿Sí o no?","Ja, bitte.","Sí, por favor."],
  ["nein","","no","nain","Nein danke.","No, gracias.","Nein, das stimmt nicht.","No, eso no es correcto.","Auf keinen Fall! Nein!","¡De ninguna manera! ¡No!"],
  ["genau","","exacto / exactamente","ge-náu","Genau!","¡Exacto!","Das ist genau richtig.","Eso es exactamente correcto.","Genau das meine ich.","Exactamente eso es lo que quiero decir."],
  ["eigentlich","","en realidad / la verdad es que","ái-gent-lij","Eigentlich weiß ich das nicht.","En realidad no lo sé.","Was willst du eigentlich?","¿Qué es lo que realmente quieres?","Eigentlich bin ich müde.","La verdad es que estoy cansada."],
  ["einfach","","simple / sencillamente / solo","áin-faj","Das ist einfach.","Es sencillo.","Einfach super!","¡Simplemente genial!","Mach es einfach!","¡Hazlo sin más!"],
  ["irgendwie","","de alguna manera / algo","ír-gend-vi","Das ist irgendwie komisch.","Eso es de alguna manera raro.","Ich fühle mich irgendwie müde.","Me siento algo cansada.","Irgendwie klappt das.","De alguna manera funciona."],
  ["übrigens","","por cierto","ü-bri-gens","Übrigens, wie heißt du?","Por cierto, ¿cómo te llamas?","Übrigens, das wusste ich nicht.","Por cierto, no lo sabía.","Das ist, übrigens, nicht korrekt.","Eso, por cierto, no es correcto."],
  ["leider","","desgraciadamente / lo siento, pero...","láy-der","Leider nein.","Lo siento, pero no.","Leider kann ich nicht kommen.","Desgraciadamente no puedo venir.","Das ist leider so.","Desgraciadamente es así."],
  ["Spaß","","diversión / broma","shpas","Das macht Spaß!","¡Eso es divertido!","Viel Spaß!","¡Que te diviertas!","Das war ein Spaß.","Era una broma."],
  ["prima","","genial / estupendo","prí-ma","Das ist prima!","¡Eso es genial!","Prima, danke!","¡Estupendo, gracias!","Alles prima.","Todo estupendo."],

  // ── 471-500: Naturaleza, viajes y vocabulario final ───────────────────────
  ["das Wetter","das","el tiempo (meteorológico)","das Vé-ter","Wie ist das Wetter heute?","¿Qué tiempo hace hoy?","Das Wetter ist schön.","El tiempo es bueno.","Schlechtes Wetter.","Mal tiempo."],
  ["die Sonne","die","el sol","di Zó-ne","Die Sonne scheint.","Brilla el sol.","In der Sonne sitzen.","Sentarse al sol.","Heute scheint die Sonne.","Hoy brilla el sol."],
  ["der Regen","der","la lluvia","der Ré-gen","Es regnet.","Llueve.","Im Regen laufen.","Correr bajo la lluvia.","Der Regen hört auf.","La lluvia para."],
  ["der Schnee","der","la nieve","der Shné","Es schneit!","¡Está nevando!","Der Schnee ist weiß.","La nieve es blanca.","Viel Schnee.","Mucha nieve."],
  ["die Wolke","die","la nube","di Vól-ke","Viele Wolken heute.","Muchas nubes hoy.","Eine dunkle Wolke.","Una nube oscura.","Kein Wolken.","Sin nubes."],
  ["die Reise","die","el viaje","di Ráy-ze","Eine schöne Reise!","¡Buen viaje!","Die Reise nach Deutschland.","El viaje a Alemania.","Gute Reise!","¡Buen viaje!"],
  ["der Urlaub","der","las vacaciones","der Ú-raub","Ich mache Urlaub.","Estoy de vacaciones.","Wohin fährst du in Urlaub?","¿Adónde vas de vacaciones?","Guten Urlaub!","¡Buenas vacaciones!"],
  ["das Ticket","das","el billete / la entrada","das Tí-ket","Ich kaufe ein Ticket.","Compro un billete.","Das Ticket ist gültig.","El billete es válido.","Zwei Tickets bitte.","Dos entradas por favor."],
  ["die Sprache","die","el idioma / la lengua","di Shprá-je","Deutsch ist eine schöne Sprache.","El alemán es un idioma bonito.","Welche Sprachen sprichst du?","¿Qué idiomas hablas?","Eine Sprache lernen.","Aprender un idioma."],
  ["das Wort","das","la palabra","das Vort","Ich kenne das Wort nicht.","No conozco la palabra.","Ein neues Wort lernen.","Aprender una palabra nueva.","Was bedeutet dieses Wort?","¿Qué significa esta palabra?"]
];

// Convertir al formato de objetos
const VOCAB = VOCAB_RAW.map(r => ({
  word:          r[0],
  gender:        r[1],
  translation:   r[2],
  pronunciation: r[3],
  examples: [
    { de: r[4], es: r[5] },
    { de: r[6], es: r[7] },
    { de: r[8], es: r[9] }
  ]
}));
